require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - 'examples/**'

  # opt-in new cops
  NewCops: enable

# overrides
Layout/LineLength:
  Max: 120

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/BooleanSymbol:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  EnforcedStyle: strict

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
