#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"

Lummox::SDL.init!

window = Lummox::SDL::Window.new("A Test Window", size: [480, 360])
puts "Window created with ID #{window.id}"

processor = Lummox::SDL::EventProcessor.new
processor.listen_for(:quit) { |_event| window.close! }
processor.process_events until window.closed?

Lummox::SDL.quit!

puts "all done!"
