#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"
require "pry-byebug"

Lummox::SDL.init!

window = Lummox::SDL::Window.new("A Test Window", size: [480, 360])
puts "Window created with ID #{window.id}"

Lummox::SDL::EventDispatcher.add_event_listener(:controller_device_added) { |event| puts event.inspect }
Lummox::SDL::EventDispatcher.add_event_listener(:controller_device_removed) { |event| puts event.inspect }

Lummox::SDL::EventDispatcher.add_event_listener(:controller_device_added) { |event| Lummox::SDL::GameController.new(event.joystick_index) }
Lummox::SDL::EventDispatcher.add_event_listener(:controller_device_removed) { |event| event.game_controller.close! }

Lummox::SDL::EventDispatcher.add_event_listener(:window_event) { |event| event.window.close! if event.close? }
Lummox::SDL::EventDispatcher.dispatch_events until window.closed?

Lummox::SDL.quit!

puts "all done!"
