#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"
require "pry-byebug"

Lummox.init!

window = Lummox::Window.new("Press start to break, test controller state", size: [480, 360])
puts "Window created with ID #{window.id}"

Lummox::EventDispatcher.add_event_listener(:controller_device_added) { |event| Lummox::Controller.new(event.joystick_index) }
Lummox::EventDispatcher.add_event_listener(:controller_device_removed) { |event| event.controller.close! }

Lummox::EventDispatcher.add_event_listener(:controller_button_down) do |event|
  next unless event.button == :controller_button_start
  controller = event.controller
  puts "Test axes with controller.position(...)"
  puts "Test buttons with controller.pressed?(...)"
  binding.pry
end

Lummox::EventDispatcher.add_event_listener(:window_event) { |event| event.window.close! if event.close? }
Lummox::EventDispatcher.dispatch_events until window.closed?

Lummox.quit!

puts "all done!"
