#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"

Lummox.init!

Lummox::EventDispatcher.add_event_listener(:mouse_wheel) { |event| puts "#{event.direction} x#{event.x}" }
Lummox::EventDispatcher.add_event_listener(:mouse_wheel) { |event| puts "#{event.direction} x+#{event.x}" }
Lummox::EventDispatcher.add_event_listener(:mouse_wheel) { |event| puts "#{event.direction} y#{event.y}" }
Lummox::EventDispatcher.add_event_listener(:mouse_wheel) { |event| puts "#{event.direction} y+#{event.y}" }

Lummox::EventDispatcher.add_event_listener(:window_event) { |event| event.window.close! if event.close? }

window = Lummox::Window.new("A Test Window", size: [480, 360])
Lummox::EventDispatcher.dispatch_events until window.closed?

Lummox.quit!

puts "all done!"
