#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"

Lummox.init!

window = Lummox::Window.new("A Test Window", size: [480, 360])
puts "Window created with ID #{window.id}"

Lummox::EventDispatcher.add_event_listener(:controller_device_added) { |event| Lummox::Controller.new(event.joystick_index) }
Lummox::EventDispatcher.add_event_listener(:controller_device_removed) { |event| event.controller.close! }

Lummox::EventDispatcher.add_event_listener(:mouse_motion) { |event| puts event.inspect; }

Lummox::EventDispatcher.add_event_listener(:window_event) { |event| event.window.close! if event.close? }
Lummox::EventDispatcher.dispatch_events until window.closed?

Lummox.quit!

puts "all done!"
