#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"

Lummox.init!

size = Lummox::SDL.get_num_render_drivers
driver_infos = Array.new(size) do |i|
  info = Lummox::SDL::RendererInfo.new
  Lummox::SDL.get_render_driver_info(i, info)
  info
end


driver_infos.map do |driver_info|
  pixel_formats = driver_info.texture_formats.to_a[0...driver_info.num_texture_formats]
                             .map { |f| Lummox::PixelFormat.new(f) }

  puts "#{driver_info.name}\n--------------------"
  pixel_formats.each { |f| puts f.inspect }
end
