#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"

Lummox.init!

class Renderer
  def pointer
    :renderer_pointer
  end
end

renderer = Renderer.new

point = Lummox::Point.new(2.5, 10.3)
point.draw(renderer)
point.drawing_type = :point_float
point.draw(renderer)

rect = Lummox::Rect.new(0.5, 0.75, 10.4, 10.2)
rect.draw(renderer)
rect.drawing_type = :fill_rect
rect.draw(renderer)
rect.drawing_type = :rect_float
rect.draw(renderer)
rect.drawing_type = :fill_rect_float
rect.draw(renderer)

points = Array.new(5) { |i| Lummox::Point.new(i + 0.25, i + 0.75) }
points.drawing_type = :points
points.draw(renderer)
points.drawing_type = :points_float
points.draw(renderer)
points.drawing_type = :lines
points.draw(renderer)
points.drawing_type = :lines_float
points.draw(renderer)


rects = Array.new(5) { |i| Lummox::Rect.new(i + 0.25, i + 0.75, 2 * i + 1.3, 3 * i + 1.6) }
rects.drawing_type = :rects
rects.draw(renderer)
rects.drawing_type = :rects_float
rects.draw(renderer)
rects.drawing_type = :fill_rects
rects.draw(renderer)
rects.drawing_type = :fill_rects_float
rects.draw(renderer)

Lummox.quit!
