#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"

Lummox::SDL.init!

window = Lummox::SDL::Window.new("Text editing event tests", size: [480, 360])
puts "Window created with ID #{window.id}"

Lummox::SDL::Keyboard.text_input_enabled = true
puts "Dispatching text input events" if Lummox::SDL::Keyboard.text_input_enabled?

Lummox::SDL::EventDispatcher.add_event_listener(:text_editing) { |e| puts e.inspect }
Lummox::SDL::EventDispatcher.add_event_listener(:text_input) { |e| puts e.inspect }

Lummox::SDL::EventDispatcher.add_event_listener(:window_event) { |event| event.window.close! if event.close? }
Lummox::SDL::EventDispatcher.dispatch_events until window.closed?

Lummox::SDL.quit!

puts "all done!"
