#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"
require "ffi"

point_buffer = FFI::MemoryPointer.new(Lummox::SDL::Core::Point, 5)
[
  [1, 5],
  [2, 3],
  [5, 0],
  [2, 4],
  [10, 10]
].each_with_index do |point_data, index|
  Lummox::SDL::Core::Point.new(
    point_buffer + (index * Lummox::SDL::Core::Point.size),
    x: point_data[0], y: point_data[1]
  )
end

clip_rect = Lummox::SDL::Core::Rect.new(x: 0, y: 0, w: 6, h: 6)

output = Lummox::SDL::Core::Rect.new
ret = Lummox::SDL::Core.enclose_points(point_buffer, point_buffer.size / point_buffer.type_size, clip_rect, output)
enclosed = ret == :true

if enclosed
  puts "Enclosing Rect:"
  %i[x y w h].each { |key| puts "- #{key}: #{output[key]}" }
else
  puts "No points enclosed"
end
