#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "lummox"
require "ffi"

Lummox::SDL.init!

name = "A Test Window"
window = Lummox::SDL::Core.create_window(
  name,
  Lummox::SDL::Core::WINDOW_POS_CENTERED, Lummox::SDL::Core::WINDOW_POS_CENTERED,
  480, 360,
  Lummox::SDL::Core::WINDOW_OPENGL
)

window_id = Lummox::SDL::Core.get_window_id(window)
window_from_id = Lummox::SDL::Core.get_window_from_id(window_id)

if window == window_from_id
  puts "Passing through ID gives == window"
else
  puts "Passing through ID gives != window"
end

event = Lummox::SDL::Core::Event.new
while Lummox::SDL::Core.poll_event(event).nonzero?
  # clear out the queue
end

Lummox::SDL::Core.destroy_window(window)
Lummox::SDL.quit!

puts "all done!"
